### ISSUE TITLE
Default selected group should be based on last modified date.

### ISSUE THREAD

**Issue by fg123** [fg123/roommates#109]
As per title. I'm not sure if we actually track that right now so we might need to do that.

**Comment by fg123** [comment]
Actually, we already track the "created time" so we can just have it in reverse chronological order too. Or we can save which one the user was last "focused" on and default select that. What do you think?

**Comment by robertpan226** [comment]
Last modified would probably be more relevant for the user? Cause "dead" groups would naturally bubble down near the bottom. We currently only track when the group was created, and it should be an easy fix to add the last modified date.

**Comment by fg123** [comment]
Alright, would you be able to implement that? Any non `GET` requests should update the last modified on a group. I can also implement a front-end cookie that saves the last tab / group the user selected so it persists among refreshes.

**Comment by robertpan226** [comment]
Yeah, I can probably get a PR up by tonight. But we’re gonna have to remake the 181 Winter group

**Comment by fg123** [comment]
You're resetting the field every time anyway, why does it need to be remade? We can just run a script to repopulate that field in the DB.

**Comment by robertpan226** [comment]
True, also we should only modify the field when a non-get request is successful right?
